### ISSUE TITLE
Need to download jboss-eap-6.4.4-patch.zip package from the Customer Support Portal

### ISSUE THREAD

**Issue by gmershad** [jbossdemocentral/bpms-customer-evaluation-demo#18]
Need to download jboss-eap-6.4.4-patch.zip package from the Customer Support Portal
and place it in the D:\KIE\bpms-customer-evaluation-demo-master\installs directory to proceed...

We are unable to get patch.zip

**Comment by eschabell** [comment]
@gmershad, this is not being maintained anymore here it seems, but you can get updated and containerized version with downloads of product available on Red Hat Developers site here:

https://github.com/redhatdemocentral/rhcs-customer-evaluation-demo

Hope this offers you a chance to learn with this example.
